frr version 10.7.0
frr defaults traditional
hostname service-host
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.40/32
 ip address 10.20.0.10/24
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf cost 9
!
interface eth1
 description TO-CORE1-PRIMARY
 ip address 10.0.3.1/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf cost 1
!
interface eth2
 description TO-CORE2-BACKUP
 ip address 10.0.3.3/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf cost 21
!
router ospf
 ospf router-id 10.255.0.40
 passive-interface lo
!
line vty
!
