global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: telconet
    metrics_path: /metrics
    scrape_interval: 1s
    static_configs:
      - targets:
          - api:8000
