frr version 10.7.0
frr defaults traditional
hostname access1
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.11/32
 ip ospf area 0.0.0.0
!
interface eth1
 description TO-AGG1-PRIMARY
 ip address 10.0.1.0/31
 ip ospf area 0.0.0.0
 ip ospf cost 10
!
interface eth2
 description TO-AGG2-BACKUP
 ip address 10.0.1.2/31
 ip ospf area 0.0.0.0
 ip ospf cost 100
!
interface eth3
 description CUSTOMER-A
 ip address 10.10.1.1/24
 ip ospf area 0.0.0.0
!
router ospf
 ospf router-id 10.255.0.11
 passive-interface lo
 passive-interface eth3
!
line vty
!

