frr version 10.7.0
frr defaults traditional
hostname access2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.12/32
 ip ospf area 0.0.0.0
!
interface eth1
 description TO-AGG1-BACKUP
 ip address 10.0.1.4/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf cost 100
!
interface eth2
 description TO-AGG2-PRIMARY
 ip address 10.0.1.6/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
 ip ospf hello-interval 1
 ip ospf dead-interval 4
 ip ospf cost 10
!
interface eth3
 description CUSTOMER-B
 ip address 10.10.2.1/24
 ip ospf area 0.0.0.0
!
router ospf
 ospf router-id 10.255.0.12
 passive-interface lo
 passive-interface eth3
!
line vty
!
