frr version 10.7.0
frr defaults traditional
hostname core1
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.31/32
 ip ospf area 0.0.0.0
!
interface eth1
 description TO-AGG1-PRIMARY
 ip address 10.0.2.1/31
 ip ospf area 0.0.0.0
 ip ospf cost 10
!
interface eth2
 description TO-AGG2-BACKUP
 ip address 10.0.2.5/31
 ip ospf area 0.0.0.0
 ip ospf cost 100
!
interface eth3
 description TO-CORE2
 ip address 10.0.2.8/31
 ip ospf area 0.0.0.0
 ip ospf cost 20
!
interface eth4
 description SERVICE-NETWORK
 ip address 10.20.0.1/24
 ip ospf area 0.0.0.0
 ip ospf cost 10
!
router ospf
 ospf router-id 10.255.0.31
 passive-interface lo
 passive-interface eth4
!
line vty
!
