frr version 10.7.0
frr defaults traditional
hostname agg1
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.21/32
 ip ospf area 0.0.0.0
!
interface eth1
 description TO-ACCESS1
 ip address 10.0.1.1/31
 ip ospf area 0.0.0.0
 ip ospf cost 10
!
interface eth2
 description TO-ACCESS2
 ip address 10.0.1.5/31
 ip ospf area 0.0.0.0
 ip ospf cost 100
!
interface eth3
 description TO-CORE1-PRIMARY
 ip address 10.0.2.0/31
 ip ospf area 0.0.0.0
 ip ospf cost 10
!
interface eth4
 description TO-CORE2-BACKUP
 ip address 10.0.2.2/31
 ip ospf area 0.0.0.0
 ip ospf cost 100
!
router ospf
 ospf router-id 10.255.0.21
 passive-interface lo
!
line vty
!

